from pathlib import Path
p=Path('Assets/ARRift/Runtime/FrameSampler.cs');s=p.read_text(encoding='utf-8-sig')
s=s.replace('public long timestamp;','public long timestamp;public GestureFrame metadata;')
s=s.replace('float next,slow;long lastTimestamp;','long nextId,lastTimestamp;readonly ARFrameDeadline deadline=new ARFrameDeadline();bool sampling=true;')
s=s.replace('slow=Time.unscaledDeltaTime>1f/27?slow+Time.unscaledDeltaTime:Mathf.Max(0,slow-Time.unscaledDeltaTime*.25f);bool low=slow>5||adaptive!=null&&(adaptive.ThermalLimited||adaptive.Reduced);','bool low=adaptive!=null&&adaptive.Reduced;')
s=s.replace('pending=writing;PreviewPixels(b);','b.metadata.convertReadyMs=GestureRecognizerBridge.Now;pending=writing;PreviewPixels(b);')
s=s.replace('if(pending>=0&&bridge!=null&&!bridge.Busy)','if(!sampling){pending=-1;return;}\n            if(pending>=0&&bridge!=null&&!bridge.Busy)')
s=s.replace('bridge.Submit(b.pixels,b.size.x,b.size.y,b.rotation,b.timestamp,b.display,b.hasDisplay)','bridge.Submit(b.pixels,b.metadata)')
s=s.replace('if(converting||Time.unscaledTime<next||bridge==null||cameraManager==null)return;next=Time.unscaledTime+1f/TargetHz;','if(converting||bridge==null||cameraManager==null||!deadline.Due(Time.realtimeSinceStartupAsDouble,TargetHz))return;')
s=s.replace('try{writing=pending>=0?', 'try{if(!deadline.Unique(image.timestamp))return;writing=pending>=0?')
s=s.replace('float scale=(float)LongEdge/Mathf.Max(image.width,image.height);','float scale=Mathf.Min(1,(float)LongEdge/Mathf.Max(image.width,image.height));')
s=s.replace('b.hasDisplay=hasDisplay;var parameters=', 'b.hasDisplay=hasDisplay;b.metadata=new GestureFrame{epoch=bridge.Epoch,frameId=++nextId,timestampMs=b.timestamp,sensorTimestamp=image.timestamp,acquireMs=GestureRecognizerBridge.Now,width=b.size.x,height=b.size.y,rotation=b.rotation,displayMatrix=b.display,hasDisplayMatrix=b.hasDisplay};var parameters=')
s=s.replace('void OnDisable(){','public void SetSamplingActive(bool value){if(sampling==value)return;sampling=value;pending=-1;deadline.Reset(Time.realtimeSinceStartupAsDouble);bridge?.SetSamplingActive(value);}\n        void OnDisable(){')
p.write_text(s,encoding='utf-8')
Path('Assets/ARRift/Runtime/GestureRecognizerBridge.cs').write_text(Path('Tools/ar_goia_bridge.cs.txt').read_text(encoding='utf-8'),encoding='utf-8')
