from pathlib import Path
exec(Path('Tools/ar_m5_runtime_patch.py').read_text().split("core='Assets/")[0])
p=Path('Assets/Skills/Core/Runtime/SkillVfxPool.cs');s=p.read_text()
s=s.replace('void Awake(){WarmUp();}', 'AR.ARCombatContext ar;float Scale=>ar!=null?ar.scale:1;float SessionNow=>ar!=null?ar.Now:Time.time;\n        void Awake(){ar=GetComponent<AR.ARCombatContext>();WarmUp();}')
s=s.replace('static void ConfigureAudio','void ConfigureAudio').replace('a.minDistance=3;a.maxDistance=35','a.minDistance=3*Scale;a.maxDistance=35*Scale')
s=s.replace('n.Radius=radius;', 'n.Radius=radius*Scale;')
s=s.replace('n.root.transform.localScale=Vector3.one;', 'n.root.transform.localScale=Vector3.one/(ar!=null?Scale:1);')
s=s.replace('if(nodes==null)return;\n            bool reduced=', 'if(nodes==null||ar!=null&&ar.Paused)return;\n            bool reduced=')
s=s.replace('n.dimUntil>Time.time','n.dimUntil>SessionNow').replace('Time.time+seconds','SessionNow+seconds')
s=s.replace('if(nodes==null)return null;', 'if(nodes==null)return null;')
s=s.replace('main.startSpeed=new ParticleSystem.MinMaxCurve(1,4)', 'main.startSpeed=new ParticleSystem.MinMaxCurve(Scale,4*Scale)')
s=s.replace('shape.radius=.15f','shape.radius=.15f*Scale')
s=s.replace('main.startSize=new ParticleSystem.MinMaxCurve(kind==SkillVfxKind.FireBloom?.9f:.06f,kind==SkillVfxKind.FireBloom?1.4f:.18f)', 'main.startSize=new ParticleSystem.MinMaxCurve((kind==SkillVfxKind.FireBloom?.9f:.06f)*Scale,(kind==SkillVfxKind.FireBloom?1.4f:.18f)*Scale)')
s=s.replace('point-Vector3.up*.4f','point-Vector3.up*(.4f*Scale)').replace('n.End=Random.onUnitSphere*Random.Range(1,3)+Vector3.up*1.2f','n.End=(Random.onUnitSphere*Random.Range(1,3)+Vector3.up*1.2f)*Scale')
s=s.replace('new Vector3(.62f,1.05f,.58f);n.model.localPosition=Vector3.up*1.02f;Circle(n,n.Position,.65f,', 'new Vector3(.62f,1.05f,.58f)*Scale;n.model.localPosition=Vector3.up*(1.02f*Scale);Circle(n,n.Position,.65f*Scale,')
for num in ['.025f','.02f','.17f']:s=s.replace('Vector3.up*'+num, 'Vector3.up*('+num+'*Scale)')
s=s.replace('Vector3.down*(n.age*n.age*4)', 'Vector3.down*(n.age*n.age*4*Scale)')
s=s.replace('Mathf.Clamp01(n.age/.24f)*1.15f','Mathf.Clamp01(n.age/.24f)*1.15f*Scale').replace('n.line.widthMultiplier=.14f','n.line.widthMultiplier=.14f*Scale')
s=s.replace('Mathf.Cos(a)*r,.15f,Mathf.Sin(a)*r','Mathf.Cos(a)*r,.15f*Scale,Mathf.Sin(a)*r').replace('Vector3.up*(smoke?.75f:1.1f)','Vector3.up*((smoke?.75f:1.1f)*Scale)')
s=s.replace('e.startSize=frost?Random.Range(.7f,1.2f):smoke?Random.Range(.9f,1.6f):Random.Range(.8f,1.6f);', 'e.startSize=(frost?Random.Range(.7f,1.2f):smoke?Random.Range(.9f,1.6f):Random.Range(.8f,1.6f))*Scale;')
s=s.replace('Mathf.Cos(a)*radius,.04f,Mathf.Sin(a)*radius','Mathf.Cos(a)*radius,.04f*Scale,Mathf.Sin(a)*radius').replace('Vector3.up*.04f','Vector3.up*(.04f*Scale)')
s=s.replace('(n.kind==SkillVfxKind.ChainBolt?.65f:.23f)','((n.kind==SkillVfxKind.ChainBolt?.65f:.23f)*Scale)')
s=s.replace('(.5f+.4f*Mathf.Sin(i*13.4f+phase))','(.5f+.4f*Mathf.Sin(i*13.4f+phase))*Scale')
s=s.replace('coreWidth*=n.Radius','coreWidth*=n.Radius/Scale')
# Draw scales fixed widths. Radius-derived bolt widths already have world units.
s=s.replace('reaction?coreWidth*1.85f:n.kind==SkillVfxKind.ChainBolt?coreWidth*1.65f:.42f*n.Radius','reaction?coreWidth*1.85f:n.kind==SkillVfxKind.ChainBolt?coreWidth*1.65f:.42f*n.Radius/Scale')
s=s.replace('(n.kind==SkillVfxKind.Bell?.85f:.15f)+Mathf.Sin(a*3)*.16f','((n.kind==SkillVfxKind.Bell?.85f:.15f)+Mathf.Sin(a*3)*.16f)*Scale')
s=s.replace('Vector3.down*1.65f+radial*Random.Range(6,9)','(Vector3.down*1.65f+radial*Random.Range(6,9))*Scale').replace('e.velocity=-radial*3+Vector3.Cross(Vector3.up,radial)*8+Vector3.up*.35f','e.velocity=(-radial*3+Vector3.Cross(Vector3.up,radial)*8+Vector3.up*.35f)*Scale')
s=s.replace('e.startSize=Random.Range(.3f,.55f)','e.startSize=Random.Range(.3f,.55f)*Scale').replace('-radial*(2+distance*.65f)+Vector3.Cross(Vector3.up,radial)*8+Vector3.up*.35f','-radial*(2*Scale+distance*.65f)+(Vector3.Cross(Vector3.up,radial)*8+Vector3.up*.35f)*Scale')
s=s.replace('r=Mathf.Lerp(8.5f,1.4f,t)','r=Mathf.Lerp(8.5f,1.4f,t)*Scale').replace('-1.65f+t*1.3f','(-1.65f+t*1.3f)*Scale')
s=s.replace('Vector3.up*.3f;e.velocity=new Vector3(Mathf.Cos(a),.1f,Mathf.Sin(a))*15','Vector3.up*(.3f*Scale);e.velocity=new Vector3(Mathf.Cos(a),.1f,Mathf.Sin(a))*15*Scale').replace('e.startSize=.35f','e.startSize=.35f*Scale')
s=s.replace('static void Draw(LineRenderer','void Draw(LineRenderer').replace('l.widthMultiplier=width;color.a=alpha','l.widthMultiplier=width*Scale;color.a=alpha')
p.write_text(s)
p=Path('Assets/Skills/GiantHandSeal/Runtime/GiantHandVisual.cs');s=p.read_text()
s=s.replace('float nextContour;', 'float nextContour;AR.ARCombatContext ar;float Scale=>ar!=null?ar.scale:1;float SessionNow=>ar!=null?ar.Now:Time.time;')
s=s.replace('config=c;owner=caster;', 'config=c;owner=caster;ar=caster!=null?caster.GetComponent<AR.ARCombatContext>():null;')
s=s.replace('source.minDistance=5;source.maxDistance=35','source.minDistance=5*Scale;source.maxDistance=35*Scale').replace('contour.widthMultiplier=0.028f','contour.widthMultiplier=0.028f*Scale')
s=s.replace('main.startSize=new ParticleSystem.MinMaxCurve(mist?0.08f:0.045f,mist?0.32f:0.2f)','main.startSize=new ParticleSystem.MinMaxCurve((mist?0.08f:0.045f)*Scale,(mist?0.32f:0.2f)*Scale)').replace('main.gravityModifier=mist?0.1f:0.65f','main.gravityModifier=(mist?0.1f:0.65f)*Scale')
for num in ['.6f','0.08f','0.06f','0.11f','.26f','0.015f','0.15f','0.12f']:s=s.replace('Vector3.up*'+num,'Vector3.up*('+num+'*Scale)')
s=s.replace('target.height+0.04f','target.height+0.04f*Scale').replace('target.height-0.08f','target.height-0.08f*Scale').replace('Mathf.Lerp(target.height-0.3f,0.18f,','Mathf.Lerp(target.height-0.3f*Scale,0.18f*Scale,')
s=s.replace('),0.8f,(1-summon)', '),0.8f*Scale,(1-summon)')
s=s.replace('inward?1.6f*target.visualScale:Random.Range(0.1f,1.4f)', 'inward?1.6f*target.visualScale:Random.Range(0.1f,1.4f)*Scale')
s=s.replace('*speed*Random.Range(0.5f,1)','*speed*Random.Range(0.5f,1)*Scale').replace('for(int i=0;i<count;i++)','if(ar!=null)count=Mathf.CeilToInt(count*.5f);\n            for(int i=0;i<count;i++)')
s=s.replace('"_Progress",Time.time','"_Progress",SessionNow').replace('Time.time>=nextContour','SessionNow>=nextContour').replace('nextContour=Time.time','nextContour=SessionNow')
p.write_text(s)
print('M5 VFX scale patch applied')
