from pathlib import Path
p=Path('Assets/Levels/Runtime/LevelDirector.cs');s=p.read_text(encoding='utf-8').replace('if (!Gameplaying() || CinematicPaused || AwaitingSkySword) return;', 'if (!Gameplaying() || CinematicPaused) return;').replace('Elapsed += Time.deltaTime;', 'Elapsed += Time.deltaTime;\n            if(AwaitingSkySword)return;').replace('yield return new WaitForSeconds(winDelay);', 'yield return new WaitForSeconds(Level.index>=8?Mathf.Max(winDelay,2.25f):winDelay);');p.write_text(s,encoding='utf-8')
p=Path('Assets/SkyBeast/Runtime/HeavenSwordCinematic.cs');s=p.read_text(encoding='utf-8').replace('Pause(cycle.Ground);Pause(cycle.GetComponent<FireBreathVisuals>());Pause(scheduler.GetComponent<SkyStrikePool>());','Pause(cycle.GetComponent<FireBreathVisuals>());').replace('Playing=true;Active=this;', 'Playing=true;Active=this;Cursor.lockState=CursorLockMode.None;Cursor.visible=true;').replace('targetAnimator.speed=p>=.70f&&p<.80f?.10f:targetSpeed;', 'targetAnimator.speed=HitApplied&&(p-.735f)*duration<.065f?0:p>=.70f&&p<.80f?.10f:targetSpeed;').replace('if(camera!=null){camera.transform.SetPositionAndRotation', 'UIStateManager.Instance?.RefreshCursor();\n            if(camera!=null){camera.transform.SetPositionAndRotation')
p.write_text(s,encoding='utf-8')
p=Path('Assets/SkyBeast/Runtime/BurningGround.cs');s=p.read_text(encoding='utf-8-sig').replace('void Update()\n        {', 'void Update()\n        {\n            if(FireBreathCycle.Instance!=null&&FireBreathCycle.Instance.CinematicPaused){foreach(var p in pool)if(p.active)p.expires+=Time.deltaTime;return;}');p.write_text(s,encoding='utf-8')
p=Path('Assets/SkyBeast/Runtime/Attacks/SkyStrikePool.cs');s=p.read_text(encoding='utf-8-sig').replace('void Update(){', 'void Update(){if(FireBreathCycle.Instance!=null&&FireBreathCycle.Instance.CinematicPaused)return;');p.write_text(s,encoding='utf-8')
p=Path('Assets/MonsterShaban/Scripts/PlayerMonsterHealth.cs');s=p.read_text(encoding='utf-8-sig').replace('if (info.amount <= 0 || currentHealth <= 0) return false;', 'if(CampusRift.SkyBeast.HeavenSwordCinematic.Active!=null&&CampusRift.SkyBeast.HeavenSwordCinematic.Active.Playing)return false;\n            if (info.amount <= 0 || currentHealth <= 0) return false;');p.write_text(s,encoding='utf-8')
p=Path('Assets/CampusRiftUI/Runtime/UIStateManager.cs');s=p.read_text(encoding='utf-8-sig').replace('if (Keyboard.current != null && Keyboard.current.escapeKey.wasPressedThisFrame)', 'if (Keyboard.current != null && Keyboard.current.escapeKey.wasPressedThisFrame && !(SkyBeast.HeavenSwordCinematic.Active!=null&&SkyBeast.HeavenSwordCinematic.Active.Playing))');p.write_text(s,encoding='utf-8')
# Add descriptive level objective while holding the cleared wave.
p=Path('Assets/CampusRiftUI/Runtime/LevelHUD.cs');s=p.read_text(encoding='utf-8-sig').replace('BodyText = body;', 'if(director.AwaitingSkySword){title=vn?"THIÊN KIẾM":"HEAVEN SWORD";body=vn?"Đợt đã sạch · Kiếm Ý đầy\\nRa ngoài trời và triệu hồi Thiên Kiếm":"Wave cleared · Sword Intent full\\nGo outdoors and summon the Heaven Sword";}\n            BodyText = body;');p.write_text(s,encoding='utf-8')
