"""Summarize preserved raw files without changing assertions or results."""
import json,pathlib,collections,re
root=pathlib.Path('.');out=root/'Artifacts/V2/P17-regression'
rows=json.loads((out/'Summary.json').read_text(encoding='utf-8'))
def n(v):
 return len(v) if isinstance(v,list) else v if isinstance(v,int) else '—'
def escape(s):return str(s).replace('|','/').replace('\n',' ')
lines=['# P17 · Hồi quy MVP — 2026-10-03','','Mỗi suite chức năng hiện có một lượt; phiên Play mới cho từng suite. Không nới assertion, không chạy lại suite cũ sau sửa. Raw và console: [P17-regression](P17-regression/). [Baseline P00](Baseline.md). Các smoke nhỏ P17 kiểm riêng phần sửa, không thay kết quả harness.','',
'Không chứng nhận toàn bộ PASS: xem các FAIL/timeout và giới hạn dưới đây. Runner có một lỗi namespace trước khi SkyVictory được launch; lỗi runner lưu riêng, không tính thành lượt harness thứ hai. SkillSet1/Pool được thu kết quả từ lần đã launch sau khi dừng orchestrator, không relaunch.','',
'| Suite | Kết quả raw | PASS / FAIL | Ghi chú / raw |','|---|---|---|---|']
for row in rows:
 name=row['name'];result=row['status'];note='';passed=row.get('passed');failed=row.get('failed')
 if row.get('hunterReport'):
  passed=row['hunterReport']['passed'];failed=row['hunterReport']['failed'];result='FAIL' if failed else 'PASS'
 if name=='LightningFlash':
  data=json.loads((out/'LightningFlash.json').read_text(encoding='utf-8-sig'));values=[data[k] for k in ('cast','piercesThree','immune','wallStops','poolStable')];passed=values.count(True);failed=values.count(False);note='Đếm 5 điều kiện boolean; wallStops=False'
 if name=='UILayout':result='PASS';note='Chỉ 1 control active trong lượt audit; không xem là ma trận HUD đầy đủ'
 if name in ('ShabanNavigation','ShabanTraversal'):
  raw_text=(out/(name+'.txt')).read_text(encoding='utf-8-sig');passed=len(re.findall(r'^.*? PASS:',raw_text,re.M));failed=len(re.findall(r'^.*? FAIL:',raw_text,re.M))
 if name=='MobileChase':
  raw_text=(out/'MobileChase.txt').read_text(encoding='utf-8-sig');result='FAIL' if '=False' in raw_text else 'PASS';passed=raw_text.count('=True');failed=raw_text.count('=False');note='4 điều kiện True; stability False giống raw trước P17'
 elif name.startswith('ShabanHunt-'):
  raw_text=(out/(name+'.txt')).read_text(encoding='utf-8-sig');hit=re.search(r'reacquiredAt=(-?[\d.]+)',raw_text);result='PASS' if hit and float(hit.group(1))>=0 else 'FAIL';note='Định tính: reacquiredAt='+hit.group(1) if hit else 'Thiếu RESULT'
 if row.get('summary')=='TIMEOUT':note='Timeout; kết quả từng phần'
 report=row.get('report');raw=pathlib.Path(report).name if report else next((p.name for p in out.glob(name+'-DONE.*')),'')
 if not raw and name.startswith('Hunter-'):raw=next((p.name for p in out.glob(name+'-*.json') if not p.name.endswith('-console.json')),'')
 if raw:note+=(' · ' if note else '')+'[raw](P17-regression/'+raw+')'
 lines.append('| '+escape(name)+' | '+result+' | '+str(n(passed))+' / '+str(n(failed))+' | '+note+' |')
lines+=['','## FAIL và đối chiếu','','- **BoostEnergy**: HUD exhaustion 18/1 giống P00, HUD cũ đã thay.','- **ShabanTraversal**: hai tuyến X F1↔F11 chọn đi bộ thay vì lift; cùng baseline, vẫn tới đích.','- **PhantomDecoy**: lượt này PASS; baseline cửa Entrance E không ổn định vẫn là giới hạn, không tuyên bố đã sửa.','- **ShabanBehavior**: 19/0 với cấu hình max range hiện tại, P00 từng 18/1.','- **MobileControls**: maxscale/notch 40/1 là lỗi bố trí có thật. Đã giới hạn trong safe area và dịch hai nút; smoke cùng điều kiện sau sửa contained=True, overlaps=False/13 vùng. Giữ raw FAIL ban đầu.','- **PlayerCombat**: 62/4 ở pointer thủ công (0,0), nằm ngoài hit area tròn từ UI comic. Smoke touch tại tâm attack/hold/dodge/lock đều True; không nới bộ lọc và không sửa fixture cũ.','- **LevelFlow**: 54/3 ở giả định TimeEscalation/L8 scaling/single-wave victory cũ; L8 hiện phải qua các giai đoạn rồng và Thiên Kiếm. Đối chiếu Level8to10 riêng.','- **SkyVictory**: 8 PASS/1 FAIL rồi timeout. Fixture cũ LoadMainMenu→OpenSettings khi hiện đang Hub, không mở được Settings, Apply với Draft null. Không sửa harness hoặc đổi luồng Sảnh để chiều test. Sky preview/apply/cancel tám bước trước đó đạt; Hub/settings smoke P17 riêng đạt.','']
for row in rows:
 if row['status'] not in ('FAIL','ERROR','TIMEOUT') or row['name'] in ('BoostEnergy','ShabanTraversal','MobileControls','PlayerCombat','LevelFlow','SkyVictory'):continue
 failed=row.get('failed');lines.append('- **'+row['name']+'**: '+escape('; '.join(failed) if isinstance(failed,list) else row.get('summary') or row.get('exception') or failed)+'. Xem raw; không che FAIL.')
lines+=['','## Phần không chạy theo TEST-POLICY','','- EnemyRoster: 50 seeds/wave; P12Balance: bot cân bằng nhiều vòng; standalone/GPU/fire benchmarks: bỏ.','- UIPlayValidation, ComicReview, ComicOutcome: tạo ma trận ảnh nhiều độ phân giải/ngôn ngữ. Bỏ nguyên harness, giữ nguyên code; thay bằng smoke Hub/Layout/Settings/Look và ảnh P17. UIPlay baseline vốn dừng ở CREDITS, 8/2.','- Các capture P13–P16, FirePerformance/FireCpu và ComicPerformance: benchmark/ma trận; bỏ.','- Runner composite V2/Learning chỉ bao các suite con đã chạy, không chạy trùng. LearningFollowup không còn class trên disk.','',
'## Smoke phần mới','','- P17: 23/0; related: 11/0; text audit 0 issue ở ảnh; raw hai lượt fixture đầu giữ task/p17.','- Touch tâm nút: 4 điều kiện True; notch fix: contained=True, overlaps=False.','- Release gate clone: valid PASS, placeholder chapter/lesson/invalid ID BLOCKED. Build Android negative thực tế Failed/2 build errors với thông báo placeholder. Cleanup asset sau BuildPlayer cần load lại theo path; đã restore byte từ backup.','',
'Các PASS chức năng không chứng minh cân bằng người chơi, duyệt học thuật hoặc FPS Android. T03/T05/T06 vẫn ⏳.']
lines=[x.replace('hai tuyến X F1↔F11 chọn đi bộ thay vì lift; cùng baseline, vẫn tới đích.','chỉ tuyến X F11→F1 chọn đi bộ thay vì lift; vẫn tới đích. Baseline P00 từng hai FAIL, lượt này 9/1.') for x in lines]
lines+=['','## Giải thích fixture rig/menu','','- Đính chính ShabanTraversal: lượt này 9 tuyến PASS/1 FAIL X F11→F1 (tới đích nhưng đi bộ). Tuyến lên X F1→F11 đã PASS, khác hai FAIL của P00.','- MobileChase: 4 điều kiện chase/cast/pursuit True; số đối tượng/material/inventory stable False. Raw ngay trước P17 cũng False, khác baseline P00; không ghi nhầm thành 5 điều kiện đạt. Đếm Material toàn scene gồm VFX đang hết lifetime, không chỉ HUD.','- SkillSet1Edges trước P17: 26/3 (camera low orbit, gather, repulsion); lượt này 25/4 (camera low orbit, lift/restore/cancel rig). P12 đã sửa VisualRig sang wrapper con khi Animator ở gameplay root; fixture Edges vẫn đo Animator.transform. Runtime BlackHole không đổi trong P17. Raw lịch sử giữ trong historical/, không thay kết quả 25/4 bằng smoke.','- EnemyReactionAnimation: kiểm lean tại Animator root thay vì wrapper hiện tại; nav/recoil phần còn lại xem raw.','- Localization: fixture cũ dereference nút PLAY trong UI cũ ngay dòng60, 0/1; UI comic/Hub hiện tại và preview VN/EN của P17 được smoke riêng. Không xác nhận 27 bước cũ đã chạy.','- LightningFlash raw wallStops=False; probe trực tiếp sau full reload, gameplay camera thật dừng3.585m, wallStops=True. Rig Hắc Động nâng/phục hồi True, navFailures0. Không rerun hai suite cũ và không dùng probe để thay raw.','- P12Fix1VisualSmoke: boss panel giữa màn, Pause ở trái; yêu cầu chỉ tách dọc đã lỗi thời sau LOOK. BossHealthBarUI giống byte trước P17; raycast/click Pause vẫn đạt.','- SkyPresence cũ mong dragon020/time-return; P16 dùng phase bắt đầu023 và Thiên Kiếm chuyển phase. Fire42/0, Sky58/0, Sword41/0, Level8to10 87/0.','- ShelterAudit: 2086/2126 (98,11853%), 40 điểm biên còn sai như audit P13. Không sửa geometry/NavMesh; đây là giới hạn đã ghi cho bản thử.','- Hunter-Lifts: raw10/1, closed shaft0/12 giữ nguyên. Probe trực tiếp mới sau full domain+scene reload dùng đúng graph lobby và path query: blocked12/12, origins walkable12/12,22guards, Console0 (task/p17/lift-direct-probe.json). Probe đầu dùng lobby suy ra cũng12/12, lưu riêng; setup RPC đầu timeout trước probe, tiếp tục phiên đã mở. Không chạy lại suite. Carving ổn trong scene mới; khác biệt vòng đời/đồng bộ fixture là suy luận, chưa chứng minh nguyên nhân cụ thể. Hunter tổng65/1 raw, Stairs232/0, Doors1012/0.','- LevelData184/1: authored total L3=13 khác bảng14. Dữ liệu không đổi trong P17; DEV thực tế spawn/clear L3=14 đạt, LevelDirector thêm ShabanElite ở wave thứ3. Không đổi balance theo validator lỗi thời.','- EnemyData: validator coi Shaban variants như minion dù có ShabanEnemyBridge; duplicate tieu-yeu là bản Data và Resources/P12 dùng summon Boss. Không xóa asset runtime này. Learning content gate độc lập0errors0warnings.','',
'Lưu ý sai sót vận hành: EnemyAbilitiesPlayTest đã chạy 33/0 gồm vòng cuối 50 zones/trial vì chưa đọc hết trước launch. Raw giữ nguyên; không chạy lại và không dùng số liệu này để tuyên bố cân bằng P17. Các suite còn lại được rà trước launch.']
lines=[x.replace('**LightningFlash**: .','**LightningFlash**: 4/1, wallStops=False.') for x in lines]
evaluated=collections.Counter(line.split(' | ')[1] for line in lines if line.startswith('| ') and line.split(' | ')[1] in ('PASS','FAIL'))
lines[6:6]=['Đủ71 suite/nhóm: đánh giá '+str(evaluated['PASS'])+' PASS / '+str(evaluated['FAIL'])+' FAIL (gồm timeout); raw runner40 PASS /16 DONE /15 FAIL. DONE được đọc theo kết quả thực tế, không mặc định PASS. Không tích checkbox “không có FAIL mới”.','']
lines+=['','## Native build','','Android/Windows dev+release: 4/4 Succeeded,0 lỗi build. Package guard verification đạt cả4. Windows dev native Hub+màn1, study/buy và reopen QA save PASS; release startup6s, không exception. APK chưa chạy trên thiết bị. Xem [BUILD-INDEX](../P17-Builds/BUILD-INDEX.md).']
(root/'Artifacts/V2/Regression-MVP.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
(root/'Artifacts/V2/MVP-Regression.md').write_text('# Hồi quy MVP\n\nBáo cáo đầy đủ: [Regression-MVP.md](Regression-MVP.md). Raw không sửa: [P17-regression](P17-regression/).\n',encoding='utf-8')
print(collections.Counter(r['status'] for r in rows),len(rows))
